baseURL = "https://r0ss0n3r1xd4t.github.io"
defaultContentLanguage = "en"
title = "r0ss0n3r1"
author = "Nguyen Huu Dat"
theme = "risotto"
locale = "en"
enableInlineShortcodes = true

sectionPagesMenu = "main"

[pagination]
pagerSize = 10

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel   = 3
    ordered    = true

[params]
  [params.theme]
    palette = "base16-dark"
  [params.about]
    title = "datxmilanista"
    description = "The best defense is a good understanding of the attack"
    logo = "👾"

[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/r0ss0n3r1xd4t"

[[params.socialLinks]]
icon = "fa-brands fa-facebook"
title = "Facebook"
url = "https://www.facebook.com/mrdatdepzai"

[[params.socialLinks]]
icon = "fa-brands fa-linkedin"
title = "LinkedIn"
url = "https://www.linkedin.com/in/nguyen-huu-dat-5a7b90281/"

[[params.socialLinks]]
icon = "fa-brands fa-discord"
title = "Discord"
url = "https://discord.com/users/babyovaltine"

[[params.socialLinks]]
icon = "fa-solid fa-envelope"
title = "Email"
url = "mailto:datxmilanista@gmail.com"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "about"
    url = "/about/"
    weight = 20
  [[menu.main]]
    identifier = "categories"
    name = "categories"
    url = "/categories/"
    weight = 30

[taxonomies]
  category = "categories"
  series = "series"
